apiVersion: blabla
kind: Sha256sumTransformer
metadata:
  name: foobar
  annotations:
    config.kubernetes.io/function: |
      exec: 
        path: sha256sum-transformer.py
spec:
    files:
    - ../files
    annotation: "goovyChecksum"
    kind:
    - Deployment
